USE CLEANING;

CREATE TABLE ECOMMERCE_ORDER(
ORDER_ID VARCHAR(40),
CUSTOMER_NAME VARCHAR(40),
EMAIL VARCHAR(40),
PHONE VARCHAR (40),
CITY VARCHAR(40),
STATE VARCHAR(40),
PRODUCT_NAME VARCHAR(40),
CATEGORY VARCHAR(40),
PRICE VARCHAR(40),
QUANTITY VARCHAR(40),
ORDER_DATE VARCHAR(40),
DELIVERY_DATE VARCHAR(40),
PAYMENT_METHOD VARCHAR(40),
ORDER_STATUS VARCHAR(40),
RATING VARCHAR(40)
);

SELECT * FROM INDIAN_ECOMMERCE;

-- Query 1. Find the Duplicates value in dataset --

SELECT ORDER_ID, COUNT(*) AS DUPLICATES
FROM INDIAN_ECOMMERCE
GROUP BY ORDER_ID
HAVING COUNT(*) > 1;

-- Query 2. Find the Empty OR null values in dataset --

SELECT * 
FROM INDIAN_ECOMMERCE
WHERE CITY IS NULL OR TRIM(CITY) = ' ';

-- Find Duplicate value in Entire Dataset -- 

SELECT SUM(CASE WHEN CITY IS NULL OR TRIM(CITY) = '' THEN 1 ELSE 0 END) AS CITY_MISSING,
SUM(CASE WHEN CATEGORY IS NULL OR TRIM(CATEGORY) = '' THEN 1 ELSE 0 END) AS CATEGORY_MISSING,
SUM(CASE WHEN PRICE IS NULL OR TRIM(PRICE) = '' THEN 1 ELSE 0 END) AS PRICE_MISSING,
SUM(CASE WHEN QUANTITY IS NULL OR TRIM(QUANTITY) = '' THEN 1 ELSE 0 END) AS QUANTITY_MISSING,
SUM(CASE WHEN RATING IS NULL OR TRIM(RATING) = '' THEN 1 ELSE 0 END) AS RATING_MISSING,
SUM(CASE WHEN ORDER_STATUS IS NULL OR TRIM(ORDER_STATUS) = '' THEN 1 ELSE 0 END) AS ORDER_STATUS_MISSING,
SUM(CASE WHEN DELIVERY_DATE IS NULL OR TRIM(DELIVERY_DATE) = '' THEN 1 ELSE 0 END) AS DELIVERY_DATE_MISSING
FROM INDIAN_ECOMMERCE;

-- Query 3. Checking issue in Other Columns (Email, Phone, Price, Quantity, Rating) --

SELECT * FROM INDIAN_ECOMMERCE
WHERE EMAIL NOT LIKE '%@%.%';

-- Phone issue -- 

SELECT * FROM INDIAN_ECOMMERCE
WHERE PHONE REGEXP "[^0-9]";

-- Price Issue --  

SELECT DISTINCT(PRICE)
FROM INDIAN_ECOMMERCE;

-- Quantity issue --

SELECT * FROM INDIAN_ECOMMERCE
WHERE QUANTITY <= 0 OR QUANTITY IS NULL;

-- Rating issue --

SELECT * FROM INDIAN_ECOMMERCE
WHERE RATING NOT BETWEEN 1 AND 5 OR RATING IS NULL;

-- Bussiness Logic -- 

SELECT * FROM INDIAN_ECOMMERCE
WHERE DELIVERY_DATE < ORDER_DATE;

-- Date Formatt -- 

SELECT DISTINCT ORDER_DATE FROM INDIAN_ECOMMERCE;

-- Date formatt in Delivery Date --

SELECT DISTINCT DELIVERY_DATE FROM INDIAN_ECOMMERCE;

-- Fix Date Formatt from Order Date -- 

UPDATE INDIAN_ECOMMERCE
SET ORDER_DATE = 
CASE
	WHEN ORDER_DATE LIKE '%-%-%'
    	THEN STR_TO_DATE(ORDER_DATE, '%d-%m-%Y')       
	WHEN ORDER_DATE LIKE '%/%/%'
		THEN STR_TO_DATE(ORDER_DATE, '%Y/%m/%d')
	WHEN ORDER_DATE LIKE '^(A-Za-z)'
		THEN STR_TO_DATE(ORDER_DATE, '%m %d %Y')
		ELSE NULL 
END;

-- Fix Date Formatt from Delivery Date --

UPDATE INDIAN_ECOMMERCE
SET DELIVERY_DATE =
CASE 
	WHEN DELIVERY_DATE LIKE '%-%-%'
    	THEN STR_TO_DATE(DELIVERY_DATE, '%d-%m-%Y')
	WHEN DELIVERY_DATE LIKE '%/%/%'
		THEN STR_TO_DATE(DELIVERY_DATE, '%Y/%m/%d')
		ELSE NULL
END;

-- Remove Duplicates --

DELETE FROM INDIAN_ECOMMERCE
WHERE ORDER_ID IN(
SELECT ORDER_ID
FROM(
SELECT ORDER_ID, ORDER_DATE, 
ROW_NUMBER() OVER(PARTITION BY ORDER_ID ORDER BY ORDER_DATE) AS Row_Numbers
FROM INDIAN_ECOMMERCE) AS t
WHERE Row_Numbers > 1
);

-- Replace the Empty values in Delivery Date Columns -- 

UPDATE INDIAN_ECOMMERCE
SET DELIVERY_DATE = DATE_ADD(ORDER_DATE, INTERVAL 5 DAY)
WHERE DELIVERY_DATE IS NULL;

-- Replace the Empty values in Order Date Columns -- 

UPDATE INDIAN_ECOMMERCE
SET ORDER_DATE = DATE_SUB(DELIVERY_DATE, INTERVAL -5 DAY)
WHERE ORDER_DATE IS NULL;

-- Clean null value from the Date columns --

DELETE FROM INDIAN_ECOMMERCE
WHERE ORDER_DATE IS NULL 
	AND DELIVERY_DATE IS NULL;

-- Clean name -- 

UPDATE INDIAN_ECOMMERCE
SET CUSTOMER_NAME = CONCAT(
UPPER(LEFT(TRIM(CUSTOMER_NAME),1)),
LOWER(SUBSTRING(TRIM(CUSTOMER_NAME),2))
);

-- Clean Emails --

UPDATE INDIAN_ECOMMERCE
SET EMAIL = LOWER(EMAIL);

DELETE FROM INDIAN_ECOMMERCE
WHERE EMAIL NOT LIKE '%@%.%';

-- Clean Phone --

UPDATE INDIAN_ECOMMERCE
SET PHONE = REPLACE(PHONE, '+91-', '+91 ');

-- Standardize the city -- 

UPDATE INDIAN_ECOMMERCE
SET CITY = UPPER(TRIM(CITY));

-- Standardize the Category --

UPDATE INDIAN_ECOMMERCE
SET CATEGORY = UPPER(TRIM(CATEGORY));

-- Clean Price --

UPDATE INDIAN_ECOMMERCE
SET PRICE = TRIM(
				REPLACE(
					REPLACE(
						REPLACE(PRICE, 'rs',''),
					'â‚¹',''),
				',','')
			);

UPDATE INDIAN_ECOMMERCE
SET PRICE = 0
WHERE PRICE NOT REGEXP '^[0-9] + (\\.[0-9]+)?$';

-- Fix the Quantity --

UPDATE INDIAN_ECOMMERCE
SET QUANTITY = 1
WHERE QUANTITY IS NULL OR QUANTITY <= 0;

-- Fix Rating -- 

UPDATE INDIAN_ECOMMERCE
SET RATING = 1
WHERE RATING NOT BETWEEN 1 AND 5;

ALTER TABLE INDIAN_ECOMMERCE
MODIFY ORDER_ID INT;

ALTER TABLE INDIAN_ECOMMERCE
MODIFY CUSTOMER_NAME VARCHAR(100),
MODIFY PHONE VARCHAR(15),
MODIFY CITY VARCHAR(20),
MODIFY STATE VARCHAR(50),
MODIFY PRODUCT_NAME VARCHAR(100),
MODIFY CATEGORY VARCHAR(50),
MODIFY PRICE DECIMAL(10,2),
MODIFY QUANTITY INT,
MODIFY ORDER_DATE DATE,
MODIFY DELIVERY_DATE DATE,
MODIFY PAYMENT_METHOD VARCHAR(20),
MODIFY ORDER_STATUS VARCHAR(50),
MODIFY RATING INT;

DESCRIBE INDIAN_ECOMMERCE;

SELECT * FROM INDIAN_ECOMMERCE;
